KUBECONFIG="/scaleoutsean/.kube/config"
SF_USERNAME="admin"
SF_PASSWORD="admin"
SF_IP="192.168.1.30"
SF_TARGET_PORTAL="192.168.103.30:3260"
NO_EXECUTE="true"
LOG_LEVEL="debug"
WAIT_TIME=5

export KUBECONFIG
export SF_IP
export SF_USERNAME
export SF_PASSWORD
export SF_TARGET_PORTAL
export NO_EXECUTE
export LOG_LEVEL
export WAIT_TIME
